### ISSUE TITLE
ログインのロード画面にreload的なものがあると良さそう？

### ISSUE THREAD

**Issue by rossy0213** [kinc-shinshu/acsu-login#2]
学校のネットワークがたまにログインしにくいので、
レスポンスが中々帰ってこない時に、一々アプリを消したりするの必要が出てくる。
レスポンス待ち中は🌀だけではなく、POSTし直すボタン追加しても良さそうだと思ってる。

**Comment by arsley** [comment]
POST処理を非同期にして、n秒待っても応答なければ「再試行」的なボタン表示するとか?
